### ISSUE TITLE
不支持windows

### ISSUE THREAD

**Issue by mushan0x0** [YangHanlin/oss-deployment-action#17]
<img width="1055" alt="image" src="https://github.com/YangHanlin/oss-deployment-action/assets/29084441/c8299658-06ed-4fd4-85d5-9eb766e63504">

**Comment by YangHanlin** [comment]
感谢提出 issue。目前确实暂未考虑 Windows 和 macOS 平台的情况，不过应该可以加上。

**Comment by yanghanlin** [comment]
@mushan0x0 现在应该已经支持 Windows 和 macOS runner 了，可以重新试下。

**Comment by mushan0x0** [comment]
好的感谢
